
CREATE DATABASE IF NOT EXISTS train_ticket;
USE train_ticket;

-- Users table
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

-- Stations table (with station_code as second field)
CREATE TABLE stations (
    station_id INT AUTO_INCREMENT PRIMARY KEY,
    station_name VARCHAR(100) NOT NULL,
    station_code VARCHAR(10) NOT NULL ,
    distance INT NOT NULL,
    fare INT NOT NULL
);

-- Bookings table
CREATE TABLE bookings (
    pnr INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    source_station_id INT NOT NULL,
    destination_station_id INT NOT NULL,
    booking_time DATETIME NOT NULL,
    fare INT NOT NULL,
    qr_code_path VARCHAR(255) NOT NULL,
    ticket_class ENUM('first','second') DEFAULT 'second',
    is_return BOOLEAN DEFAULT FALSE,
    booking_date DATE DEFAULT (CURRENT_DATE),
    status VARCHAR(20) DEFAULT 'confirmed',
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (source_station_id) REFERENCES stations(station_id),
    FOREIGN KEY (destination_station_id) REFERENCES stations(station_id)
);



INSERT INTO stations (station_name, station_code, distance, fare) VALUES
('Churchgate', 'CCG', 0, 5),
('Marine Lines', 'MEL', 2, 5),
('Charni Road', 'CYR', 3, 5),
('Grant Road', 'GTR', 4, 5),
('Mumbai Central', 'MMCT', 5, 10),
('Mahalakshmi', 'MX', 6, 10),
('Lower Parel', 'PL', 7, 10),
('Prabhadevi', 'PBHD', 8, 10),
('Dadar', 'D/DR/DDR', 9, 10),
('Matunga Road', 'MRU', 10, 10),
('Mahim Jn', 'MM', 11, 15),
('Bandra', 'B/BA', 12, 15),
('Khar Road', 'KHAR', 13, 15),
('Santacruz', 'STC', 14, 15),
('Vile Parle', 'VLP', 15, 15),
('Andheri', 'A/AD/ADH', 18, 20),
('Jogeshwari', 'JOS', 20, 20),
('Ram Mandir', 'RMAR', 22, 20),
('Goregaon', 'GMN', 24, 20),
('Malad', 'MDD', 26, 25),
('Kandivali', 'KLE', 28, 25),
('Borivali', 'BO/BVI', 30, 25),
('Dahisar', 'DIC', 32, 30),
('Mira Road', 'MIRA', 35, 30),
('Bhayander', 'BY', 38, 30),
('Naigaon', 'NIG', 40, 35),
('Vasai Road', 'BSR/BS', 45, 40),
('Nalla Sopara', 'NSP', 48, 40),
('Virar', 'VR', 52, 45),
('Vaitarna', 'VTN', 55, 50),
('Saphale', 'SAH', 58, 50),
('Kelve Road', 'KLV', 60, 55),
('Palghar', 'PLG', 65, 60),
('Umroli Road', 'UOI', 70, 65),
('Boisar', 'BOR', 75, 70),
('Vangaon', 'VGN', 80, 75),
('Dahanu Road', 'DRD', 85, 80),

-- Insert stations from Central 1 Line
('CSMT', 'CSMT/ST', 0, 5),
('Masjid', 'MSD', 1, 5),
('Sandhurst Road', 'SNRD', 2, 5),
('Byculla', 'BY', 3, 5),
('Chinchpokli', 'CHG', 4, 5),
('Currey Road', 'CRD', 5, 10),
('Parel', 'PR', 6, 10),
('Dadar', 'D/DR/DDR', 7, 10),
('Matunga', 'MTN', 8, 10),
('Sion', 'SIN', 9, 10),
('Kurla', 'C/CH', 10, 10),
('Vidhyavihar', 'VVH', 12, 15),
('Ghatkopar', 'G', 14, 15),
('Vikhroli', 'VK', 16, 15),
('Kanjur Marg', 'KJMG', 18, 20),
('Bhandup', 'BND', 20, 20),
('Nahur', 'NHU', 22, 20),
('Mulund', 'MLND', 24, 20),
('Thane', 'TNA', 26, 25),
('Kalva', 'KLVA', 28, 25),
('Mumbra', 'MBQ', 30, 25),
('Diva Jn', 'DIVA', 32, 30),
('Kopar', 'KOPR', 34, 30),
('Dombivli', 'DI', 36, 30),
('Thakurli', 'THK', 38, 35),
('Kalyan', 'KYN', 40, 35),
('Vithalwadi', 'VLDI', 42, 40),
('Ulhas Nagar', 'ULNR', 44, 40),
('Ambernath', 'ABH', 46, 40),
('Badalpur', 'BUD', 48, 45),
('Vangani', 'VGI', 50, 45),
('Shelu', 'SHLU', 52, 50),
('Neral', 'NRL', 54, 50),
('Bhivpuri Road', 'BVS', 56, 55),
('Karjat', 'KJT/S', 58, 55),
('Palasdhari', 'PDI', 60, 60),
('Kelavli', 'KLY', 62, 60),
('Dolavli', 'DLV', 64, 65),
('Lowjee', 'LWJ', 66, 65),
('Khopoli', 'KP', 68, 70),

-- Insert stations from Central 2 Line
('CSMT', 'CSMT/ST', 0, 5),
('Masjid', 'MSD', 1, 5),
('Sandhurst Road', 'SNRD', 2, 5),
('Byculla', 'BY', 3, 5),
('Chinchpokli', 'CHG', 4, 5),
('Currey Road', 'CRD', 5, 10),
('Parel', 'PR', 6, 10),
('Dadar', 'D/DR/DDR', 7, 10),
('Matunga', 'MTN', 8, 10),
('Sion', 'SIN', 9, 10),
('Kurla', 'C/CH', 10, 10),
('Vidhyavihar', 'VVH', 12, 15),
('Ghatkopar', 'G', 14, 15),
('Vikhroli', 'VK', 16, 15),
('Kanjur Marg', 'KJMG', 18, 20),
('Bhandup', 'BND', 20, 20),
('Nahur', 'NHU', 22, 20),
('Mulund', 'MLND', 24, 20),
('Thane', 'TNA', 26, 25),
('Kalva', 'KLVA', 28, 25),
('Mumbra', 'MBQ', 30, 25),
('Diva Jn', 'DIVA', 32, 30),
('Kopar', 'KOPR', 34, 30),
('Dombivli', 'DI', 36, 30),
('Thakurli', 'THK', 38, 35),
('Kalyan', 'KYN', 40, 35),
('Shahad', 'SHAD', 42, 40),
('Ambivli', 'ABY', 44, 40),
('Titwala', 'TLA', 46, 40),
('Khadavli', 'KDV', 48, 45),
('Vasind', 'VSD', 50, 45),
('Asangaon', 'ASO', 52, 50),
('Atagaon', 'ATG', 54, 50),
('Thansit', 'THS', 56, 55),
('Khardi', 'KE', 58, 55),
('Umbermali', 'OMB', 60, 60),
('Kasara', 'KSRA', 62, 60),

-- Insert stations from Harbour Line
('CSMT', 'CSMT/ST', 0, 5),
('Masjid', 'MSD', 1, 5),
('Sandhurst Road', 'SNRD', 2, 5),
('Dockyard Road', 'DKRD', 3, 5),
('Reay Road', 'RRD', 4, 5),
('Cotton Green', 'CTGN', 5, 10),
('Sewri', 'SVE', 6, 10),
('Vadala Road', 'VDLR', 7, 10),
('GTB Nagar', 'GTBN', 8, 10),
('Chunabhatti', 'CHF', 9, 10),
('Kurla', 'C/CH', 10, 10),
('Tilaknagar', 'TKNG', 11, 15),
('Chembur', 'CMBR', 12, 15),
('Govandi', 'GV', 13, 15),
('Mankhurd', 'MNKD', 14, 15),
('Vashi', 'VSH', 16, 20),
('Sanpada', 'SNCR', 17, 20),
('Juinagar', 'JNJ', 18, 20),
('Nerul', 'NEU', 19, 20),
('Seawood Darave', 'SWDV', 20, 20),
('Belapur CBD', 'BEPR', 22, 25),
('Kharghar', 'KHAG', 24, 25),
('Mansarovar', 'MANR', 26, 25),
('Khandeshwar', 'KNDS', 28, 30),
('Panvel', 'PNVL', 30, 30),

-- Insert stations from Trans Harbour Line
('Thane', 'TNA', 0, 5),
('Airoli', 'AIRL', 8, 10),
('Rabale', 'RABE', 10, 10),
('Ghansoli', 'GNSL', 12, 15),
('Koparkhairane', 'KPHN', 14, 15),
('Turbhe', 'TUH', 16, 15),
('Juinagar', 'JNJ', 18, 20),
('Nerul', 'NEU', 20, 20),
('Seawood Darave', 'SWDV', 22, 25),
('Belapur CBD', 'BEPR', 24, 25),
('Kharghar', 'KHAG', 26, 25),
('Mansarovar', 'MANR', 28, 30),
('Khandeshwar', 'KNDS', 30, 30),
('Panvel', 'PNVL', 32, 35),

-- Insert stations from Uran Line
('Nerul', 'NEU', 0, 5),
('Seawood Darave', 'SWDV', 2, 5),
('Belapur CBD', 'BEPR', 4, 5),
('Bamandongri', 'BMNDG', 6, 10),
('Kharkopar', 'KARP', 8, 10),

-- Insert stations from Diva-Roha Line
('Diva Jn', 'DIVA', 0, 5),
('Dativali', 'DTVL', 3, 5),
('Nilje', 'NIIJ', 6, 10),
('Taloja Panchanand', 'TPND', 9, 10),
('Navade Road', 'NVRD', 12, 15),
('Kalamboli', 'KLMG', 15, 15),
('Panvel', 'PNVL', 18, 20),
('Somtane', 'SMNE', 21, 25),
('Rasayani', 'RSYI', 24, 25),
('Apta', 'APTA', 27, 30),
('Jite', 'JITE', 30, 30),
('Hamarapur', 'HPUR', 33, 35),
('Pen', 'PEN', 36, 35),
('Kasu', 'KASU', 39, 40),
('Nagothane', 'NGTN', 42, 40),
('Nidi', 'NIDI', 45, 45),
('Roha', 'ROHA', 48, 45),

-- Insert stations from Dahanu-Virar-Panvel Line
('Dahanu Road', 'DRD', 0, 5),
('Vangaon', 'VGN', 5, 10),
('Boisar', 'BOR', 10, 10),
('Umroli Road', 'UOI', 15, 15),
('Palghar', 'PLG', 20, 20),
('Kelva Road', 'KLV', 25, 25),
('Saphale', 'SAH', 30, 30),
('Vaitarna', 'VTN', 35, 35),
('Virar', 'VR', 40, 40),
('Nalla Sopara', 'NSP', 45, 45),
('Vasai Road', 'BSR/BS', 50, 50),
('Juchandra Road', 'JCNR', 55, 55),
('Kaman Road', 'KARD', 60, 60),
('Kharbao', 'KHBV', 65, 65),
('Bhiwandi Road', 'BIRD', 70, 70),
('Kopar', 'KOPR', 75, 75),
('Dativali', 'DTVL', 80, 80),
('Nilje', 'NIIJ', 85, 85),
('Taloja Panchanand', 'TPND', 90, 90),
('Navade Road', 'NVRD', 95, 95),
('Kalamboli', 'KLMG', 100, 100),
('Panvel', 'PNVL', 105, 105),

-- Insert stations from Neral-Matheran Line
('Neral', 'NRL', 0, 5),
('Jumapatti', 'JTT', 3, 5),
('Waterpipe', 'WTP', 6, 10),
('Aman Lodge', 'AMNA', 9, 10),
('Matheran', 'MAE', 12, 15);

select* from stations;
select* from users;
select* from bookings;


